### ISSUE TITLE
Expose server metrics to Prometheus

### ISSUE THREAD

**Issue by fabian-marquardt** [kif-ev/oskiosk-server#108]
Expose statistics about bought products to a Prometheus Server so that we can display some fancy graphs with Grafana Dashboards.

- See here for a formal definition of the data format: https://prometheus.io/docs/instrumenting/exposition_formats/
- And here some examples for the official Ruby client: https://github.com/prometheus/client_ruby#usage

**Comment by thegcat** [comment]
Im afraid the library isn't well suited to our use-case, as it is rather geared towards more "classical" metrics rather than "dump the current state of what has been consumed".

I think I have an idea how to provide statistics though.

**Comment by thegcat** [comment]
This seems to work as a basic endpoint.
