### ISSUE TITLE
Add an additional scope for deposit stations with access to the users.json endpoint

### ISSUE THREAD

**Issue by fabian-rump** [kif-ev/oskiosk-server#61]
Currently the deposit station can only search for a given identifier and retrieve the resulting user. Obviously it makes sense to have a user list at the deposit station, i.e. for users who lost their identifier code.

**Comment by thegcat** [comment]
The `deposit` scope is intended for an anonymous deposit station in a KdV setting (trust-based checkout, trust-based deposit). In that case having access to the whole user list is an information leak.

A manned deposit station should be able do use the `admin` scope currently, or do you see any problem with that?

**Comment by fabian-rump** [comment]
Well, regarding the proposed API enhancements in #62 there should definitely be a privilege separation  between the station for doing deposits and the station for administrating the whole system, i.e. adding/changing/deleting users and product.

So right now using the admin scope should work just fine, but for the future I would rather not grant that access level to such a station.

**Comment by fabian-rump** [comment]
So maybe the right solution for the future is to add an additional scope "between" `deposit` and `admin`?

**Comment by thegcat** [comment]
That's what I was thinking. `manned_deposit` sounds clunky though. `cash_desk`?

**Comment by fabian-rump** [comment]
`cash_desk` +1

**Comment by thegcat** [comment]
Added in 8588e1c
