### ISSUE TITLE
Add endpoints to provide CRUD functionality for users/products/identifiers

### ISSUE THREAD

**Issue by fabian-rump** [kif-ev/oskiosk-server#62]
Currently the API only provides read access to the user, product and identifier models. Defining new objects is only possible with direct access to the server backend. For a more more convenient administration of the system, it should be possible to create or modify these objects using the API.

**Comment by thegcat** [comment]
Product creation is implemented in #77, The API Docs for that should be up-to-date shortly, the dev server on heroku too.

**Comment by thegcat** [comment]
Product update is implemented in #81, the API Docs for that should be up-to-date shortly, the dev server on heroku too.

**Comment by thegcat** [comment]
There are now also user write endpoints, identifiers can be created through products or users.
