### ISSUE TITLE
Update to Ruby 2.4.1

### ISSUE THREAD

**Issue by fabian-rump** [kif-ev/oskiosk-server#87]
The current Ruby version in Alpine Linux (used for the Docker container) is 2.4.1. Can we upgrade the Gemfile to this version or are there any problems with the new version?

In addition: Is there a proper way to tell bundler that the newer version is ok anyway?

**Comment by thegcat** [comment]
> The current Ruby version in Alpine Linux (used for the Docker container) is 2.4.1. Can we upgrade the Gemfile to this version or are there any problems with the new version?

I guess, I'll give it a quick try.

> In addition: Is there a proper way to tell bundler that the newer version is ok anyway?

Yep.

**Comment by thegcat** [comment]
Solved in #89
