### ISSUE TITLE
Cannot remove existing pricings, identifers, etc.

### ISSUE THREAD

**Issue by fabian-marquardt** [kif-ev/oskiosk-server#90]
For existing products there is only the PATCH endpoint /products/<id>.json which works fine for changing or adding stuff. However one can not remove e.g. identifiers with this one. We should add a POST or PUT endpoint for the same URL which completely replaces the product with the provided object. The same should probably be done for users.

**Comment by fabian-rump** [comment]
Somewhat related to this one: Currently there is no DELETE endpoint for products and users. This should obviously exist as well. However there are good reasons why we might not want to completely remove this data from the server. Maybe we can talk about this next week, deletion does not seem to be a critical issue.

**Comment by thegcat** [comment]
Do you need this for next week, and if so what is the use-case?

Rails does not by default differentiate between PUT and PATCH, and the current implementation supports only patch-style/additive updates for simplicity (of the client) 's sake.

**Comment by fabian-rump** [comment]
Not a critical feature. Let's do this next week in person. Just keeping track of stuff I encountered.

**Comment by thegcat** [comment]
Re-reading the spec I just realised I misinterpreted the meanings of PUT and PATCH though, and it seems both should do full updates, i.e. fully replaces passed fields.

Is this time-critical or can we hack on it next week?

**Comment by thegcat** [comment]
> Let's do this next week in person.

OK :-)

**Comment by thegcat** [comment]
See #101 for a proposal to be able to remove pricings and identifiers from products and users.

**Comment by thegcat** [comment]
Solved in #101
